import { test } from "node:test";
import assert from "node:assert/strict";
import { createTestDb } from "../../db/test-helpers.ts";
import { getOwner } from "../../domain/users.ts";
import { createProjectWithIdea, updateProjectStatus, getProject } from "../../domain/projects.ts";
import { createTask } from "../../domain/tasks.ts";
import { createArtifact } from "../../domain/project-outputs.ts";
import { upsertModelRegistryEntry, recordModelHealthCheck } from "../../domain/model-registry.ts";
import { classifyConversation } from "../intent.ts";
import { converse, contextualEvidence } from "../orchestrator.ts";
import { conversation, boundedHistory, consume } from "../memory.ts";
import { conversationCandidates, answerWithFreeModel, conversationInput } from "../model.ts";
import { sealMemory, restoreMemory } from "../remote-memory.ts";
import { confirmedRemoteTransition } from "../remote-actions.ts";
process.env.OFFICE_OWNER_EMAIL="conversation@example.test";
process.env.OFFICE_OWNER_PASSWORD_HASH="synthetic";
function fixture(){const t=createTestDb();const ownerId=getOwner(t.db)!.id;const {project}=createProjectWithIdea(t.db,{ownerId,title:"Counter",rawIdeaText:"A local counter with increment and reset."});return {...t,project,scope:{ownerId,sessionId:"login-one",projectId:project.id,roleId:"solution-architect"}};}
test("intent precedence keeps reads separate from mutations and covers required categories",()=>{
  for(const [text,kind] of [["Create a counter","CREATE_PROJECT"],["Pause this project","PROJECT_CONTROL"],["Approve this","APPROVAL_ACTION"],["What needs my approval?","STATUS_QUERY"],["Open Classic Office","WORKSPACE_ACTION"],["Which model are you using?","MODEL_QUERY"],["Why did you choose it?","EXPLANATION"],["Can Developer fix that?","REASONING"],["What are you working on?","AGENT_WORK_QUERY"],["Did QA pass?","PROJECT_QUERY"],["Show QA's report","ARTIFACT_QUERY"],["Is the worker running?","OFFICE_QUERY"],["Write a function","CODING_QUESTION"],["Find vulnerabilities","SECURITY_QUESTION"],["Suggest tests","QA_QUESTION"],["Hello","GENERAL_CONVERSATION"],["","UNKNOWN"]])assert.equal(classifyConversation(text),kind,text);
});
test("status, delivery, costs and model answers never call a provider",async()=>{const t=fixture();let calls=0;try{for(const text of ["Status","Did QA pass?","Is it delivered?","What are you working on?","Which model are you using?","How much has this project cost?","What needs my approval?"]){const r=await converse(t.db,t.scope,{text,mode:"local"},{fetchImpl:async()=>{calls++;throw Error();}});assert.equal(r.source,"state");assert.ok(r.message);}assert.equal(calls,0);}finally{t.close();}});
test("missing QA evidence is not a pass; unverified delivery is not called verified",async()=>{const t=fixture();try{assert.match((await converse(t.db,t.scope,{text:"Did QA pass?",mode:"local"})).message,/No QA task/);assert.match((await converse(t.db,t.scope,{text:"Is it delivered?",mode:"local"})).message,/NOT_STARTED/);}finally{t.close();}});
test("memory is login, owner, role and project scoped and bounded",()=>{const t=fixture();try{const row=conversation(t.db,t.scope);for(const change of [{ownerId:"other"},{sessionId:"other"},{projectId:null},{roleId:"qa-agent"}])assert.throws(()=>conversation(t.db,{...t.scope,...change},row.id));const history=boundedHistory(Array.from({length:100},()=>({role:"user" as const,text:"x".repeat(4000)})));assert.ok(history.length<=12);assert.ok(history.reduce((n,m)=>n+m.text.length,0)<=10000);}finally{t.close();}});
test("project isolation rejects unknown and foreign context before provider access",async()=>{const t=fixture();try{await assert.rejects(()=>converse(t.db,{...t.scope,projectId:"missing"},{text:"Why?",mode:"local"}));await assert.rejects(()=>converse(t.db,{...t.scope,ownerId:"other"},{text:"Why?",mode:"local"}));}finally{t.close();}});
test("role context excludes artifacts from another project and configured secrets",async()=>{const t=fixture();try{const task=createTask(t.db,{projectId:t.project.id,roleId:"solution-architect",title:"Design"});const other=createProjectWithIdea(t.db,{ownerId:t.scope.ownerId,title:"Other",rawIdeaText:"PRIVATE_OTHER_REQUIREMENT"}).project;createArtifact(t.db,{projectId:other.id,type:"architecture",content:"PRIVATE_OTHER_ARTIFACT"});process.env.TEST_CONVERSATION_SECRET="secret-conversation-test-12345";createArtifact(t.db,{projectId:t.project.id,taskId:task.id,type:"architecture",content:"Design uses "+process.env.TEST_CONVERSATION_SECRET});const text=JSON.stringify(await contextualEvidence(t.db,t.scope));assert.ok(!text.includes("PRIVATE_OTHER"));assert.ok(!text.includes(process.env.TEST_CONVERSATION_SECRET));assert.match(text,/redacted/);}finally{delete process.env.TEST_CONVERSATION_SECRET;t.close();}});
test("project creation proposes an immutable single-use action without creating a project",async()=>{const t=fixture();try{const before=t.db.prepare("SELECT COUNT(*) n FROM projects").get()!.n;const r=await converse(t.db,t.scope,{text:"Create a simple counter with reset",mode:"local"});assert.equal(r.pending?.action.kind,"CREATE_PROJECT");assert.equal(t.db.prepare("SELECT COUNT(*) n FROM projects").get()!.n,before);const row=conversation(t.db,t.scope,r.conversationId);assert.equal(consume(t.db,row,"forged"),null);assert.equal(consume(t.db,row,r.pending!.token)?.kind,"CREATE_PROJECT");assert.equal(consume(t.db,row,r.pending!.token),null);}finally{t.close();}});
test("new question revokes a stale confirmation",async()=>{const t=fixture();try{const r=await converse(t.db,t.scope,{text:"Pause this project",mode:"local"});await converse(t.db,t.scope,{text:"Status",conversationId:r.conversationId,mode:"local"});assert.equal(consume(t.db,conversation(t.db,t.scope,r.conversationId),r.pending!.token),null);}finally{t.close();}});
test("no qualified model is an honest failure with zero Claude or paid calls",async()=>{const t=fixture();let calls=0;try{process.env.AI_OFFICE_CLAUDE_ENABLED="false";const r=await converse(t.db,t.scope,{text:"Why this architecture?",mode:"local"},{fetchImpl:async()=>{calls++;throw Error();}});assert.equal(r.source,"unavailable");assert.equal(calls,0);}finally{t.close();}});
test("conversation qualification never implies execution qualification; health and context still gate",()=>{const t=fixture();try{upsertModelRegistryEntry(t.db,{provider:"ollama",modelId:"small",displayName:"small",contextWindow:8192,capabilities:[]});recordModelHealthCheck(t.db,"ollama","small",{health:"HEALTHY"});t.db.prepare("INSERT INTO conversation_qualifications VALUES (?,?,?,?,?,?,?)").run("ollama","small","FAST_CONVERSATION",1,300,3000,Date.now());assert.equal(conversationCandidates(t.db,"FAST_CONVERSATION",2000).length,1);assert.equal(conversationCandidates(t.db,"REASONING",2000).length,0);assert.equal(conversationCandidates(t.db,"FAST_CONVERSATION",4000).length,0);assert.equal(t.db.prepare("SELECT qualified FROM model_registry WHERE modelId='small'").get()!.qualified,0);recordModelHealthCheck(t.db,"ollama","small",{health:"UNAVAILABLE"});assert.equal(conversationCandidates(t.db,"FAST_CONVERSATION",2000).length,0);}finally{t.close();}});
test("remote bounded memory survives hydration but rejects tampering and other logins",async()=>{const t=fixture(),u=createTestDb();process.env.OFFICE_SESSION_SECRET="test-secret-that-is-at-least-thirty-two-bytes";try{const r=await converse(t.db,t.scope,{text:"Status",mode:"local"});const token=await sealMemory(t.db,t.scope,r.conversationId);await restoreMemory(u.db,t.scope,r.conversationId,token);assert.match(conversation(u.db,t.scope,r.conversationId).messages,/Status/);await assert.rejects(()=>restoreMemory(u.db,{...t.scope,sessionId:"other"},r.conversationId,token));await assert.rejects(()=>restoreMemory(u.db,t.scope,r.conversationId,token.slice(0,-5)+"ABCDE"));}finally{t.close();u.close();}});
test("unqualified paid route cannot reach adapter even with qualifying conversation evidence",async()=>{const t=fixture();let calls=0;try{upsertModelRegistryEntry(t.db,{provider:"claude",modelId:"paid",displayName:"paid",contextWindow:8192,capabilities:[]});recordModelHealthCheck(t.db,"claude","paid",{health:"HEALTHY"});t.db.prepare("INSERT INTO conversation_qualifications VALUES (?,?,?,?,?,?,?)").run("claude","paid","REASONING",1,300,5000,Date.now());assert.equal(await answerWithFreeModel(t.db,conversationInput("orchestrator","Why?"),"REASONING",{fetchImpl:async()=>{calls++;throw Error();}}),null);assert.equal(calls,0);}finally{t.close();}});
test("remote confirmation nonce survives a later transition and refuses replay",()=>{const t=fixture();try{updateProjectStatus(t.db,t.project.id,"IN_PROGRESS");const action={kind:"PAUSE" as const,projectId:t.project.id};assert.equal(confirmedRemoteTransition(t.db,action,"nonce-one").ok,true);assert.equal(confirmedRemoteTransition(t.db,{kind:"RESUME",projectId:t.project.id},"nonce-two").ok,true);assert.equal(confirmedRemoteTransition(t.db,action,"nonce-one").ok,false);assert.equal(getProject(t.db,t.project.id)!.status,"IN_PROGRESS");}finally{t.close();}});
function qualifiedGroq(t:ReturnType<typeof fixture>,models=["chat-a","chat-b"]){
 process.env.GROQ_API_KEY="synthetic-test-key";process.env.AI_OFFICE_GROQ_FREE_TIER_CONFIRMED="true";process.env.AI_OFFICE_GROQ_FREE_MODELS=models.join(",");
 for(const modelId of models){upsertModelRegistryEntry(t.db,{provider:"groq",modelId,displayName:modelId,contextWindow:16000,capabilities:[]});recordModelHealthCheck(t.db,"groq",modelId,{health:"HEALTHY"});for(const cap of ["FAST_CONVERSATION","REASONING"])t.db.prepare("INSERT INTO conversation_qualifications VALUES (?,?,?,?,?,?,?)").run("groq",modelId,cap,1,200,8000,Date.now());}
}
function response(summary:string){return new Response(JSON.stringify({choices:[{finish_reason:"stop",message:{content:JSON.stringify({summary,artifacts:[],decisions:[],testResults:[],events:[],fileOperations:[],recommendedNextActions:[]})}}],usage:{prompt_tokens:50,completion_tokens:20}}),{status:200});}
test("follow-up includes bounded same-project history and no execution instructions",async()=>{const t=fixture();try{qualifiedGroq(t);const prompts:string[]=[];const fetchImpl:typeof fetch=async(_u,init)=>{prompts.push(String(init?.body));return response("The counter uses local state.");};const first=await converse(t.db,t.scope,{text:"Why use local state?",mode:"local"},{fetchImpl});assert.equal(first.source,"model");await converse(t.db,t.scope,{text:"Can that handle a reset?",mode:"local",conversationId:first.conversationId},{fetchImpl});assert.match(prompts[1],/Why use local state/);assert.match(prompts[1],/The counter uses local state/);assert.ok(!prompts[1].includes("real implementation work belongs"));assert.equal(t.db.prepare("SELECT tasksCompleted FROM model_registry WHERE modelId='chat-a'").get()!.tasksCompleted,0);}finally{t.close();}});
test("429 records cooldown and bounded free fallback, never raw error text",async()=>{const t=fixture();try{qualifiedGroq(t);let calls=0;const answer=await answerWithFreeModel(t.db,conversationInput("orchestrator","Explain"),"REASONING",{fetchImpl:async()=>{calls++;return calls===1?new Response(JSON.stringify({error:{message:"SECRET_PROVIDER_FAILURE"}}),{status:429,headers:{"retry-after":"60"}}):response("Grounded answer");}});assert.equal(calls,2);assert.equal(answer?.model,"chat-b");assert.ok(Number(t.db.prepare("SELECT rateLimitedUntil FROM model_registry WHERE modelId='chat-a'").get()!.rateLimitedUntil)>Date.now());assert.ok(!JSON.stringify(answer).includes("SECRET_PROVIDER_FAILURE"));}finally{t.close();}});
test("provider failure stops after two candidates; deterministic queries remain available",async()=>{const t=fixture();try{qualifiedGroq(t,["chat-a","chat-b","chat-c"]);let calls=0;const fetchImpl:typeof fetch=async()=>{calls++;throw Error("unsafe failure");};const r=await converse(t.db,t.scope,{text:"Explain the design",mode:"local"},{fetchImpl});assert.equal(calls,2);assert.equal(r.source,"unavailable");assert.ok(!r.message.includes("unsafe"));await converse(t.db,t.scope,{text:"Status",mode:"local"},{fetchImpl});assert.equal(calls,2);}finally{t.close();}});
test("model generated actions are rejected and never applied",async()=>{const t=fixture();try{qualifiedGroq(t,["chat-a"]);const result=await answerWithFreeModel(t.db,conversationInput("orchestrator","Explain"),"REASONING",{fetchImpl:async()=>new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({summary:"Created a file",fileOperations:[{kind:"file-operation",action:"write",path:"index.html",content:"unsafe"}]})}}]}),{status:200})});assert.equal(result,null);assert.equal(t.db.prepare("SELECT COUNT(*) n FROM projects").get()!.n,1);}finally{t.close();}});
test("unconfirmed account and oversized context make zero requests",async()=>{const t=fixture();try{qualifiedGroq(t);process.env.AI_OFFICE_GROQ_FREE_TIER_CONFIRMED="false";let calls=0;const fetchImpl:typeof fetch=async()=>{calls++;throw Error();};assert.equal(await answerWithFreeModel(t.db,conversationInput("orchestrator","hello"),"REASONING",{fetchImpl}),null);process.env.AI_OFFICE_GROQ_FREE_TIER_CONFIRMED="true";assert.equal(await answerWithFreeModel(t.db,conversationInput("orchestrator","x".repeat(40000)),"REASONING",{fetchImpl}),null);assert.equal(calls,0);}finally{t.close();}});

// Headquarters "Assign New Project" phase — the confirmation summary the
// Boss reviews before anything runs, for both execution modes, using the
// EXISTING createProjectAction/createRemoteProjectAction path once
// confirmed (never a second execution system).
test("CREATE_PROJECT confirmation summary is offered in BOTH local and remote mode, names the real expected workflow, and creates nothing before confirmation", async () => {
  const t = createTestDb();
  try {
    const ownerId = getOwner(t.db)!.id;
    const idea = "Create a new project to build a Task Tracker with add, complete, delete and localStorage persistence.";
    const before = t.db.prepare("SELECT COUNT(*) n FROM projects").get()!.n as number;
    for (const mode of ["local", "remote"] as const) {
      const scope = { ownerId, sessionId: `login-${mode}`, projectId: null, roleId: "orchestrator" };
      const r = await converse(t.db, scope, { text: idea, mode });
      assert.equal(r.pending?.action.kind, "CREATE_PROJECT", mode);
      assert.equal((r.pending!.action as { mode: string }).mode, mode);
      assert.match(r.message, /Goal:.*Task Tracker/i, mode);
      assert.match(r.message, mode === "remote" ? /Execution mode: Remote/ : /Execution mode: Local/, mode);
      assert.match(r.message, /Routing mode: FREE_MULTI_MODEL/, mode);
      assert.match(r.message, /Expected workflow: .*Product Owner/, mode);
      assert.match(r.message, /Claude and paid fallback are disabled/, mode);
      assert.match(r.message, /Confirm to proceed\.$/, mode);
    }
    assert.equal(t.db.prepare("SELECT COUNT(*) n FROM projects").get()!.n, before, "no project exists until a confirmation is actually consumed");
  } finally { t.close(); }
});

test("an ordinary status question is never misread as project creation", async () => {
  const t = fixture();
  try {
    const r = await converse(t.db, t.scope, { text: "What is the office status right now?", mode: "local" });
    assert.equal(r.pending, undefined);
    assert.notEqual(r.intent, "CREATE_PROJECT");
  } finally { t.close(); }
});
