import { test } from 'node:test';
import assert from 'node:assert/strict';
import { deriveOfficeTransitions,advanceQueue,emptyQueue,QUEUE_LIMIT,type TransitionEvidence } from '../office-transitions.ts';
const now=100000;
function evidence(from='product-owner',to='solution-architect'):TransitionEvidence{return {projectId:'p',verifiedDelivery:false,tasks:[{id:'a',roleId:from,dependsOn:[]},{id:'b',roleId:to,dependsOn:['a']}],runs:[{id:'ra',taskId:'a',attempt:1,startedAt:now-2000,finishedAt:now-1000,status:'SUCCEEDED'},{id:'rb',taskId:'b',attempt:1,startedAt:now,finishedAt:null,status:'RUNNING'}],remediations:[],approvals:[],incidents:[]};}
for(const [from,to] of [['product-owner','solution-architect'],['solution-architect','frontend-developer'],['backend-developer','qa-agent']])test(`recorded dependency and run: ${from} → ${to}`,()=>{const result=deriveOfficeTransitions(evidence(from,to));assert.equal(result.length,1);assert.equal(result[0].type,'HANDOFF');assert.equal(result[0].fromRole,from);assert.equal(result[0].toRole,to);});
for(const reviewer of ['qa-agent','security-reviewer','code-reviewer'])test(`${reviewer} returns real work to developer`,()=>{const e=evidence('backend-developer',reviewer);e.remediations=[{id:'failure',taskId:'b',targets:['a'],attempt:1,occurredAt:now+10}];const t=deriveOfficeTransitions(e).find(t=>t.type==='REMEDIATION')!;assert.equal(t.fromRole,reviewer);assert.equal(t.toRole,'backend-developer');assert.equal(t.evidenceId,'failure');});
test('repair completion and genuine second QA attempt produce new handoff identity',()=>{const e=evidence('backend-developer','qa-agent');const old=deriveOfficeTransitions(e)[0].id;e.runs.push({id:'ra2',taskId:'a',attempt:2,startedAt:now+10,finishedAt:now+20,status:'SUCCEEDED'},{id:'rb2',taskId:'b',attempt:2,startedAt:now+30,finishedAt:null,status:'RUNNING'});const next=deriveOfficeTransitions(e);assert.equal(next.length,2);assert.notEqual(next[1].id,old);assert.equal(next[1].attempt,2);});
test('approval request and owner authorization use actual approval timestamps',()=>{const e=evidence();e.approvals=[{id:'approval',taskId:'b',requestedBy:'orchestrator',status:'PENDING',createdAt:now,decidedAt:null}];assert.equal(deriveOfficeTransitions(e).filter(t=>t.type.startsWith('APPROVAL')).length,1);e.approvals[0].status='APPROVED';e.approvals[0].decidedAt=now+10;const t=deriveOfficeTransitions(e).find(t=>t.type==='APPROVAL_RESUME')!;assert.equal(t.fromRole,'owner');assert.equal(t.toRole,'solution-architect');assert.equal(t.status,'AUTHORIZED');});
test('real incidents and resolutions are distinct, stable transitions',()=>{const e=evidence();e.incidents=[{id:'incident',taskId:'b',status:'REPAIRING',detectedAt:now,resolvedAt:null}];assert.equal(deriveOfficeTransitions(e).filter(t=>t.type==='RECOVERY').length,0);e.incidents[0].status='RESOLVED';e.incidents[0].resolvedAt=now+5;assert.equal(deriveOfficeTransitions(e).filter(t=>['RECOVERY','INCIDENT'].includes(t.type)).length,2);});
test('delivery requires verified evidence AND succeeded release',()=>{const e=evidence('code-reviewer','release-agent');e.runs[1].status='SUCCEEDED';e.runs[1].finishedAt=now+5;assert.ok(!deriveOfficeTransitions(e).some(t=>t.type==='DELIVERY'));e.verifiedDelivery=true;assert.ok(deriveOfficeTransitions(e).some(t=>t.type==='DELIVERY'));e.runs[1].status='FAILED';assert.ok(!deriveOfficeTransitions(e).some(t=>t.type==='DELIVERY'));});
test('no evidence means no invented activity, approval, incident, retry or packet',()=>{const e=evidence();e.runs=[];assert.deepEqual(deriveOfficeTransitions(e),[]);e.tasks=[];assert.deepEqual(deriveOfficeTransitions(e),[]);});
test('dependency without completed predecessor or started successor never makes a packet',()=>{const e=evidence();e.runs[0].status='FAILED';assert.equal(deriveOfficeTransitions(e).length,0);e.runs[0].status='SUCCEEDED';e.tasks[1].dependsOn=[];assert.equal(deriveOfficeTransitions(e).length,0);});
test('bounded queue coalesces bursts, prioritizes alerts and deduplicates repeated refreshes',()=>{const t=deriveOfficeTransitions(evidence())[0];const input=Array.from({length:1000},(_,i)=>({...t,id:String(i),occurredAt:now+i,type:i===999?'INCIDENT' as const:t.type}));let state=advanceQueue(emptyQueue(),input,now+1000);assert.equal(state.current?.id,'999');assert.ok(state.pending.length<QUEUE_LIMIT);assert.equal(state.seen.length,256);state=advanceQueue(state,input,now+1001);assert.ok(state.pending.length<QUEUE_LIMIT);assert.equal(state.current?.id,'999');});
test('refresh during transition never replays; hidden and disabled consume current truth',()=>{const input=deriveOfficeTransitions(evidence());let state=advanceQueue(emptyQueue(),input,now);assert.ok(state.current);state=advanceQueue(emptyQueue(state.watermark,state.seen),input,now+1);assert.equal(state.current,null);state=advanceQueue(emptyQueue(),input,now,false);assert.equal(state.current,null);state=advanceQueue(state,input,now+1,true);assert.equal(state.current,null);});
test('stale history and future timestamps never animate; queue fully drains',()=>{const input=deriveOfficeTransitions(evidence());assert.equal(advanceQueue(emptyQueue(),input,now+30000).current,null);assert.equal(advanceQueue(emptyQueue(),input,now-1).current,null);let state=advanceQueue(emptyQueue(),input,now);state=advanceQueue(state,input,now+3000);assert.equal(state.current,null);assert.equal(state.pending.length,0);});
